NCEPLIBS-g2c: dec_png.c File Reference
dec_png.c File Reference
PNG functions.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <png.h>
#include "grib2_int.h"
Typedefs
typedef struct png_stream png_stream
Typedef for PNG stream.
Functions
int dec_png (unsigned char *pngbuf, g2int *width, g2int *height, unsigned char *cout)
Decode PNG.
void user_read_data (png_structp png_ptr, png_bytep data, png_uint_32 length)
Custom read function used so that libpng will read a PNG stream from memory instead of a file on disk.
Detailed Description
PNG functions.
Author
Stephen Gilbert
Definition in file dec_png.c.
Typedef Documentation
png_stream
typedef struct png_stream png_stream
Typedef for PNG stream.
Definition at line 1 of file dec_png.c.
Function Documentation
dec_png()
int dec_png (unsigned char * pngbuf, g2int * width, g2int * height, unsigned char * cout)
Decode PNG.
Parameters
pngbuf Pointer to PNG buffer.
width Pointer to width.
height Pointer to height.
cout Output buffer.
Returns
0 for success, error code otherwise.
Author
Stephen Gilbert
Definition at line 61 of file dec_png.c.
References user_read_data().
Referenced by pngunpack_int().
user_read_data()
void user_read_data (png_structp png_ptr, png_bytep data, png_uint_32 length)
Custom read function used so that libpng will read a PNG stream from memory instead of a file on disk.
Parameters
png_ptr Pointer to PNG.
data Pointer to data.
length Length.
Author
Stephen Gilbert
Definition at line 35 of file dec_png.c.
Referenced by dec_png().