NCEPLIBS-g2c: mkieee.c File Reference
mkieee.c File Reference
#include <stdlib.h>
#include <math.h>
#include "grib2.h"
Functions
void mkieee (g2float *a, g2int *rieee, g2int num)
This subroutine stores a list of real values in 32-bit IEEE floating point format.
Detailed Description
Author
Stephen Gilbert
Date
2002-10-29
Definition in file mkieee.c.
Function Documentation
mkieee()
void mkieee (g2float * a, g2int * rieee, g2int num)
This subroutine stores a list of real values in 32-bit IEEE floating point format.
Parameters
a Input array of floating point values.
num Number of floating point values to convert.
rieee Output array of data values in 32-bit IEEE format stored in g2int integer array. rieee must be allocated with at least 4*num bytes of memory before calling this function.
Author
Stephen Gilbert
Date
2002-10-29
Definition at line 21 of file mkieee.c.
References int_power().
Referenced by compack(), g2_addfield(), jpcpack(), misspack(), pngpack(), simpack(), and specpack().