NCEPLIBS-g2c: util.c File Reference
util.c File Reference
Internal utility functions for the g2c library.
#include "grib2_int.h"
Functions
int g2c_check_msg (unsigned char *cgrib, g2int *lencurr, int verbose)
Check for 'GRIB' at the beginning of a GRIB message, and check to see if the message is already terminated with '7777'.
Detailed Description
Internal utility functions for the g2c library.
Author
Ed Hartnett
Date
Nov 11, 2021
Definition in file util.c.
Function Documentation
g2c_check_msg()
int g2c_check_msg (unsigned char * cgrib, g2int * lencurr, int verbose)
Check for 'GRIB' at the beginning of a GRIB message, and check to see if the message is already terminated with '7777'.
Parameters
cgrib Buffer that contains the GRIB message.
lencurr Pointer that gets the length of the GRIB message.
verbose If non-zero, print any error messages to stdout.
Returns
G2C_NO_ERROR No error.
G2C_NOT_GRIB GRIB header not found.
G2C_MSG_COMPLETE GRIB message already complete.
Author
Ed Hartnett
Date
Nov 11, 2021
Definition at line 25 of file util.c.
References G2C_MSG_COMPLETE, G2C_NO_ERROR, G2C_NOT_GRIB, and gbit().
Referenced by g2_addfield(), g2_addgrid(), g2_addlocal(), and g2_gribend().