name: Intel
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop
  schedule:
    # Run monthly
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  Intel:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - compiler: "oneapi"
            image: nceplibs-develop-ubuntu-24.04-oneapi-2025.3-intel-oneapi-mpi-2021.17
          - compiler: "classic"
            image: nceplibs-develop-ubuntu-24.04-classic-2023.2.1-intel-oneapi-mpi-2021.17
    name: "(${{ matrix.compiler }})"
    container:
      image: ghcr.io/noaa-emc/ci-common-build-cache/${{ matrix.image }}
      volumes:
        - /home/runner:/root

    steps:

    - name: "Install Intel"
      shell: bash
      run: |
        cd /opt/
        ./install-intel.sh
        set -a
        source /opt/intel/oneapi/setvars.sh
        set +a
        printenv | grep -E '^[a-zA-Z_][a-zA-Z0-9_]*=' >> $GITHUB_ENV

    - name: load-env
      shell: bash
      run: |
        set -a
        source /entrypoint.sh
        set +a
        printenv | grep -E '^[a-zA-Z_][a-zA-Z0-9_]*=' >> $GITHUB_ENV

    - name: checkout
      uses: actions/checkout@v4
      with:
        path: g2c

    - name: Initialize CodeQL
      if: ${{ matrix.compiler == 'classic' }}
      uses: github/codeql-action/init@v3
      with:
        languages: cpp
        queries: +security-and-quality
          
    - name: build
      run: |
        if [ "${{ matrix.compiler }}" = "oneapi" ]; then
          export CC=icx
          export CXX=icpx
          export FC=ifx
        else
          export CC=icc
          export CXX=icpc
          export FC=ifort
        fi
        cmake -S g2c -B g2c/build
        cmake --build g2c/build --parallel 2 --verbose

    - name: Perform CodeQL Analysis
      if: ${{ matrix.compiler == 'classic' }}
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:cpp"

    - name: test
      run: ctest --test-dir g2c/build --verbose --output-on-failure --rerun-failed
