name: Linux_versions
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

jobs:
  Linux_versions:
    runs-on: ubuntu-24.04
    env:
      CXX: g++
    strategy:
      fail-fast: true
      matrix:
        jasper-version: [2.0.33, 3.0.3, 4.0.0]
        ccompiler: [clang, gcc-12]
        include:
        - jasper-version: 4.0.0
          ccompiler: gcc-14
    
    steps:
    - name: install-dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libaec-dev libpng-dev zlib1g-dev libjpeg-dev libopenjp2-7-dev
        if [[ -z $(type -P ${{ matrix.ccompiler }}) ]]; then
          sudo apt-get install ${{ matrix.ccompiler }}
        fi
        echo "CC=${{ matrix.ccompiler }}" >> $GITHUB_ENV

    - name: cache-jasper
      id: cache-jasper
      uses: actions/cache@v4
      with:
        path: ~/jasper
        key: jasper-${{ runner.os }}-${{ matrix.jasper-version }}-${{ matrix.ccompiler }}

    - name: checkout-jasper
      if: steps.cache-jasper.outputs.cache-hit != 'true'
      uses: actions/checkout@v4
      with:
        repository: jasper-software/jasper
        path: jasper
        ref: version-${{ matrix.jasper-version }}

    - name: build-jasper
      if: steps.cache-jasper.outputs.cache-hit != 'true'
      run: |
        cd jasper
        mkdir cmake_build
        cd cmake_build
        cmake .. -DCMAKE_INSTALL_PREFIX=~/jasper
        make -j2
        make install

    - name: checkout
      uses: actions/checkout@v4
      with:
        path: g2c

    - name: build
      run: |
        cd g2c
        mkdir build
        cd build
        cmake -DJasper_ROOT=~/jasper -DUSE_AEC=ON .. 
        make -j2 VERBOSE=1

    - name: test
      run: |
        set -e          
        cd $GITHUB_WORKSPACE/g2c/build
        ctest --verbose --output-on-failure --rerun-failed

