name: Linux_versions
on:
  push:
    branches:
    - develop
    paths-ignore:
    - README.md
  pull_request:
    branches:
    - develop
    paths-ignore:
    - README.md

jobs:
  Linux_versions:
    runs-on: ubuntu-latest
    env:
      CC: gcc
      CXX: g++
    strategy:
      matrix:
        jasper-version: [2.0.33, 3.0.3]
        ccompiler: [clang, gcc]
    
    steps:
    - name: install-dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libpng-dev zlib1g-dev libjpeg-dev doxygen libopenjp2-7-dev
        python3 -m pip install gcovr
        if [[ ${{ matrix.ccompiler }} == "clang" ]]; then
          sudo apt-get install clang
        fi
        

    - name: checkout-jasper
      uses: actions/checkout@v2
      with:
        repository: jasper-software/jasper
        path: jasper
        ref: version-${{ matrix.jasper-version }}

    - name: cache-jasper
      id: cache-jasper
      uses: actions/cache@v2
      with:
        path: ~/Jasper
        key: jasper-${{ runner.os }}-${{ hashFiles('jasper/VERSION') }}

    - name: build-jasper
      if: steps.cache-jasper.outputs.cache-hit != 'true'
      run: |
        if [[ ${{ matrix.ccompiler }} == "clang" ]]; then
          export CC=clang
        elif [[ ${{ matrix.ccompiler }} == "gcc" ]]; then
          export CC=gcc
        fi
        cd jasper
        mkdir cmake_build
        cd cmake_build
        cmake .. -DCMAKE_INSTALL_PREFIX=~/Jasper
        make -j2
        make install

    - name: checkout
      uses: actions/checkout@v2
      with:
        path: g2c

    - name: build
      run: |
        if [[ ${{ matrix.ccompiler }} == "clang" ]]; then
          export CC=clang
        elif [[ ${{ matrix.ccompiler }} == "gcc" ]]; then
          export CC=gcc
        fi
        cd g2c
        mkdir build
        cd build
        cmake -DJasper_ROOT=~/Jasper -DENABLE_OpenJPEG=ON .. 
        make -j2

    - name: test
      run: |
        set -e          
        cd $GITHUB_WORKSPACE/g2c/build
        ctest --verbose --output-on-failure --rerun-failed

