name: Linux_options
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop
  schedule:
    # Run monthly
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  Linux_options:
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/noaa-emc/ci-common-build-cache/nceplibs-develop-ubuntu-24.04-gcc-13-mpich-x:latest
      volumes:
        - /home/runner:/root

    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "aec_off png_off jasper_off openjpeg_off",
            options: "-DUSE_AEC=OFF -DUSE_PNG=OFF -DUSE_Jasper=OFF -DUSE_OpenJPEG=OFF"
          }
        - {
            name: "aec_on png_off jasper_off openjpeg_off",
            options: "-DUSE_AEC=ON -DUSE_PNG=OFF -DUSE_Jasper=OFF -DUSE_OpenJPEG=OFF"
          }
        - {
            name: "aec_off png_on jasper_off openjpeg_off",
            options: "-DUSE_AEC=OFF -DUSE_PNG=ON  -DUSE_Jasper=OFF -DUSE_OpenJPEG=OFF"
          }
        - {
            name: "aec_off png_off jasper_on openjpeg_off",
            options: "-DUSE_AEC=OFF -DUSE_PNG=OFF -DUSE_Jasper=ON  -DUSE_OpenJPEG=OFF"
          }
        - {
            name: "aec_off png_on jasper_on openjpeg_off",
            options: "-DUSE_AEC=OFF -DUSE_PNG=ON  -DUSE_Jasper=ON  -DUSE_OpenJPEG=OFF"
          }
        - {
            name: "aec_on png_on jasper_on openjpeg_off",
            options: "-DUSE_AEC=ON -DUSE_PNG=ON  -DUSE_Jasper=ON  -DUSE_OpenJPEG=OFF"
          }
        - {
            name: "aec_off png_off jasper_off openjpeg_on",
            options: "-DUSE_AEC=OFF -DUSE_PNG=OFF -DUSE_Jasper=OFF -DUSE_OpenJPEG=ON "
          }
        - {
            name: "aec_on png_off jasper_off openjpeg_on",
            options: "-DUSE_AEC=ON -DUSE_PNG=OFF -DUSE_Jasper=OFF -DUSE_OpenJPEG=ON "
          }
        - {
            name: "aec_off png_on jasper_off openjpeg_on",
            options: "-DUSE_AEC=OFF -DUSE_PNG=ON  -DUSE_Jasper=OFF -DUSE_OpenJPEG=ON "
          }
        - {
            name: "aec_on png_on jasper_off openjpeg_on",
            options: "-DUSE_AEC=ON -DUSE_PNG=ON  -DUSE_Jasper=OFF -DUSE_OpenJPEG=ON "
          }
        - {
            name: "aec_off png_off jasper_off openjpeg_on",
            options: "-DUSE_AEC=OFF -DUSE_PNG=OFF -DUSE_Jasper=OFF -DUSE_OpenJPEG=ON "
          }
        - {
            name: "aec_on png_on jasper_off openjpeg_on",
            options: "-DUSE_AEC=ON -DUSE_PNG=ON  -DUSE_Jasper=OFF -DUSE_OpenJPEG=ON "
          }
        - {
            name: "g2c",
            options: "-DBUILD_G2C=ON -DPTHREADS=OFF -DLOGGING=ON"
          }
        - {
            name: "g2c_pthreads",
            options: "-DBUILD_G2C=ON -DPTHREADS=ON -DLOGGING=ON"
          }
        - {
            name: "shared",
            options: "-DBUILD_SHARED_LIBS=ON"
          }

    steps:
    - name: load-env
      shell: bash
      run: |
        set -a
        source /entrypoint.sh
        set +a
        printenv | grep -E '^[a-zA-Z_][a-zA-Z0-9_]*=' >> $GITHUB_ENV

    - name: install-dependencies
      run: |
        apt-get update
        apt-get install -y gcc
        apt-get install -y libopenjp2-7-dev

    - name: checkout
      uses: actions/checkout@v4
      with:
        path: g2c

    - name: ${{ matrix.config.name }}
      run: |
        cd g2c
        mkdir build
        cd build
        export CC=gcc
        cmake ${{ matrix.config.options }} -DCMAKE_C_FLAGS="-g -fsanitize=address -Wall -Werror" -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/g2c/install -DOpenJPEG_INCLUDE_DIRS="/usr/include/openjpeg-2.5" ..
        make -j2
        ctest --verbose --output-on-failure --rerun-failed
        make install
        if [ "${{ matrix.config.options }}" = "-DBUILD_SHARED_LIBS=ON" ]; then
           ls -l $GITHUB_WORKSPACE/g2c/install/lib/lib*.so || exit 1
        else
           ls -l $GITHUB_WORKSPACE/g2c/install/lib/lib*.a || exit 1
        fi
