name: macOS Build
on: [push, pull_request]

jobs:
  macOS-build:
    runs-on: macos-latest
    env:
      CC: gcc-11
      CXX: g++-11

    steps:
    - name: install-dependencies
      run: |
        brew update
        brew install doxygen openjpeg libpng

    - name: checkout
      uses: actions/checkout@v2
      with:
        path: g2c

    - name: build
      run: |
        cd g2c
        mkdir build
        cd build
        cmake -DENABLE_DOCS=ON -DUSE_OpenJPEG=ON -DUSE_Jasper=OFF ..
        make -j2

    - name: test
      run: |
        cd $GITHUB_WORKSPACE/g2c/build
        ctest  --output-on-failure
