name: tmp
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

# Cancel in-progress workflows when pushing to a branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  developer:
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/noaa-emc/ci-common-build-cache/nceplibs-develop-ubuntu-24.04-gcc-14-mpich-x:latest
      volumes:
        - /home/runner/data:~/data

    strategy:
      fail-fast: false

    steps:
    - name: install-dependencies
      run: |
        apt-get update
        apt-get install -y gcc g++

    - name: load-env
      shell: bash
      run: |
        set -a
        source /entrypoint.sh
        set +a
        env >> $GITHUB_ENV

    - name: checkout
      uses: actions/checkout@v4
      with:
        path: g2c

    - name: cache-data
      id: cache-data
      uses: actions/cache@v4
      with:
        path: ~/data
        key: data-2

    - name: build
      run: |
        #. /entrypoint.sh
        set -x
        export CC=gcc
        cd g2c
        mkdir build && cd build
        cmake .. -DUSE_AEC=ON -DFTP_TEST_FILES=ON -DTEST_FILE_DIR=~/data \
          -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_FLAGS="-g"
        make VERBOSE=1
        ctest --verbose --output-on-failure --rerun-failed